global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ "localhost:9090" ]
  # instead of 172... put the right IP address of your host machine or the IP address of the container
  # or the IP address of the container within the docker network
  - job_name: ksqldb
    static_configs:
      - targets: [ "172.27.80.1:12345" ]
  - job_name: flink
    static_configs:
        - targets: [ "172.27.80.1:9250", "172.27.80.1:9249" ]
