{
 "title": "Nexmark ksqlDB Dashboards",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Query 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nexmark Query 1 Consumed Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_messages{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q1_19-8\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 1 Consumed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_bytes{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q1_19-8\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 1 Start Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "kafka_consumer_app_info_start_time_ms{client_id=~\".*NEXMARK_Q1.*StreamThread-1-restore-consumer\"}"
      },
      {}
     ]
    },
    {
     "title": "Nexmark Query 1 Messages per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q1_19-5\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q1_19-8\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nexmark Query 2 Consumed Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_messages{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q2_21-23\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 2 Consumed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_bytes{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q2_21-23\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 2 Start Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
     "targets": [
      {
       "expr": "kafka_consumer_app_info_start_time_ms{client_id=~\".*NEXMARK_Q2.*StreamThread-1-restore-consumer\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 2 Messages per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q2_21-23\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q2_21-20\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query 3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nexmark Query 3 Consumed Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_messages{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q3_23-41\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_messages{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q3_23-44\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 3 Consumed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_bytes{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q3_23-41\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_bytes{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q3_23-44\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 3 Start Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
     "targets": [
      {
       "expr": "kafka_consumer_app_info_start_time_ms{client_id=~\".*NEXMARK_Q3.*StreamThread-1-restore-consumer\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 3 Messages per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q3_23-35\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q3_23-38\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q3_23-41\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q3_23-44\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query 4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nexmark Query 4 Consumed Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_messages{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK_Q4_25-57\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_messages{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK_Q4_25-60\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 4 Consumed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_bytes{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK_Q4_25-57\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_bytes{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK_Q4_25-60\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 4 Start Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "kafka_consumer_app_info_start_time_ms{client_id=~\".*SUBNEXMARK_Q4.*StreamThread-1-restore-consumer\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 4 Messages per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q4_27-65\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q4_27-68\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK_Q4_25-51\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK_Q4_25-54\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK_Q4_25-57\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK_Q4_25-60\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query 5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nexmark Query 5 Placeholder",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Query 6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nexmark Query 6 Consumed Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_messages{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK_Q4_25-57\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_messages{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK_Q4_25-60\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 6 Start Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "kafka_consumer_app_info_start_time_ms{client_id=~\".*SUBNEXMARK1_Q6.*StreamThread-1-restore-consumer\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 6 Messages per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CSAS_SUBNEXMARK1_Q6_29-83\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CSAS_SUBNEXMARK1_Q6_29-86\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CSAS_SUBNEXMARK1_Q6_29-89\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q6_35-125\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q6_35-128\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK2_Q6_31-100\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK2_Q6_31-97\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK3_Q6_33-111\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 6 Consumed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_bytes{id=\"_confluent-ksql-nexmark_query_CSAS_SUBNEXMARK1_Q6_29-89\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_bytes{id=\"_confluent-ksql-nexmark_query_CSAS_SUBNEXMARK1_Q6_29-86\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query 7",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nexmark Query 7 Consumed Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_messages{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK1_Q7_37-145\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 7 Consumed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_bytes{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK1_Q7_37-145\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 7 Start Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "kafka_consumer_app_info_start_time_ms{client_id=~\".*SUBNEXMARK1_Q7.*StreamThread-1-restore-consumer\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 7 Messages per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q7_45-170\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q7_45-173\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q7_45-176\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q7_45-179\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK1_Q7_37-142\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK1_Q7_37-145\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK2_Q7_41-156\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK2_Q7_41-159\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query 8",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nexmark Query 8 Consumed Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_messages{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK2_Q8_51-204\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_messages{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK1_Q8_47-190\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 8 Consumed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_bytes{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK1_Q8_47-190\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_total_bytes{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK2_Q8_51-204\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 8 Start Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "kafka_consumer_app_info_start_time_ms{client_id=~\".*SUBNEXMARK1_Q8.*StreamThread-1-restore-consumer\"}"
      }
     ]
    },
    {
     "title": "Nexmark Query 8 Messages per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q8_55-215\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q8_55-218\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q8_55-221\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q8_55-224\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_NEXMARK_Q8_55-224\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK1_Q8_47-187\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK2_Q8_51-201\"}"
      },
      {
       "expr": "io_confluent_ksql_metrics_consumer_metrics_consumer_messages_per_sec{id=\"_confluent-ksql-nexmark_query_CTAS_SUBNEXMARK2_Q8_51-204\"}"
      }
     ]
    }
   ]
  }
 ]
}